let base = [
  {
    id: 126335,
    name: "skunk",
    type: "battle",
    locked: false,
    unlockedTime: 0,
    inGame: false,
    image: "skunk",
    shards: null,
    shardCode: "SHS",
    nftCount: 1,
    discountEnabled: false,
    discountTypeEnabled: false,
    load: true,
    lvl: 4,
    repairing: false,
  },
  {
    id: 126336,
    name: "raccoon",
    type: "battle",
    locked: false,
    unlockedTime: 0,
    inGame: false,
    image: "raccoon",
    shards: null,
    nftCount: 1,
    shardCode: "SHR",
    discountEnabled: false,
    discountTypeEnabled: false,
    load: true,
    lvl: 3,
    repairing: false,
  },
  {
    id: 126539,
    name: "hamster",
    type: "miner",
    locked: false,
    unlockedTime: 0,
    inGame: false,
    image: "hamster",
    shards: null,
    shardCode: "SHH",
    nftCount: 1,
    discountEnabled: false,
    load: true,
    discountTypeEnabled: false,
    lvl: 1,
    repairing: false,
  },
  {
    id: 126334,
    name: "ant",
    type: "battle",
    locked: false,
    unlockedTime: 0,
    inGame: false,
    image: "ant",
    shards: null,
    shardCode: "SHA",
    nftCount: 1,
    discountEnabled: false,
    load: true,
    discountTypeEnabled: false,
    lvl: 5,
    repairing: false,
  },
  {
    id: 126341,
    name: "elephantor",
    type: "battle",
    locked: false,
    unlockedTime: 0,
    inGame: false,
    image: "elephantor",
    shards: null,
    shardCode: "SHE",
    nftCount: 1,
    discountEnabled: false,
    load: true,
    discountTypeEnabled: false,
    lvl: 2,
    repairing: false,
  },
  {
    id: 126332,
    name: "wolf",
    type: "battle",
    locked: false,
    unlockedTime: 0,
    inGame: false,
    image: "wolf",
    shards: null,
    shardCode: "SHW",
    nftCount: 1,
    discountEnabled: false,
    load: true,
    discountTypeEnabled: false,
    lvl: 6,
    repairing: false,
  },
];
export default base;
